// src/pages/database/HiddenSparksDialog.svelte
<script lang="ts">
  import { untrack } from 'svelte';
  import Button from '@/components/Button.svelte';
  import Dialog from '@/components/Dialog.svelte';
  import Icon from '@/components/Icon.svelte';
  import { factorImage, factorMetadata } from '@/lib/catalog/factor-catalog';
  import WhiteFactorTypePicker from './WhiteFactorTypePicker.svelte';

  interface Props { open?: boolean; selectedFactorIds: number[]; onsave: (factorIds: number[]) => void; }
  let { open = $bindable(true), selectedFactorIds, onsave }: Props = $props();
  let draftIds = $state(untrack(() => [...selectedFactorIds]));

  function addFactors(ids: number[]): void { draftIds = [...new Set([...draftIds, ...ids])].sort((left, right) => left - right); }
  function removeFactor(id: number): void { draftIds = draftIds.filter((entry) => entry !== id); }
  function save(): void { onsave(draftIds); open = false; }
</script>

<div class="hidden-sparks-dialog">
  <Dialog mobileFill id="hidden-sparks" bind:open title="Hide Sparks" icon="eye-off" description="Choose white factors that should be hidden from every inheritance result." maxWidth="760px" maxHeight="90dvh" mobileInset="8vw" contentPadding="16px 18px" mobileContentPadding="16px 11px">
    {#snippet headerActions()}<span class="hidden-count">{draftIds.length} hidden</span>{/snippet}
    <div class="hidden-sparks-content">
      <WhiteFactorTypePicker id="hidden-sparks-browser" mode="hide" selectedFactorIds={draftIds} onadd={addFactors} onremove={removeFactor}/>
      <section class="selection-section" aria-label="Hidden sparks">
        <div class="selection-heading">
          <span><strong>Hidden sparks</strong><small>Remove a spark here to show it again.</small></span>
          {#if draftIds.length}<button type="button" class="clear-button" onclick={() => draftIds = []}>Clear all</button>{/if}
        </div>
        {#if draftIds.length}
          <div class="hidden-list">
            {#each draftIds as factorId (factorId)}
              {@const name = factorMetadata(factorId)?.text ?? `Factor ${factorId}`}
              {@const icon = factorImage(factorId)}
              <button type="button" class="hidden-chip" aria-label={`Show ${name}`} title={`Show ${name}`} onclick={() => removeFactor(factorId)}>
                {#if icon}<img src={icon} alt=""/>{/if}<span>{name}</span><Icon name="close" size={13}/>
              </button>
            {/each}
          </div>
        {:else}<div class="empty-selection"><Icon name="eye" size={16}/><span>No sparks are hidden.</span></div>{/if}
      </section>
    </div>
    {#snippet actions()}<Button variant="ghost" onclick={() => open = false}>Cancel</Button><Button icon="check" onclick={save}>Save {draftIds.length} hidden</Button>{/snippet}
  </Dialog>
</div>

<style>
  .hidden-sparks-dialog{display:contents}
  .hidden-sparks-dialog :global(.dialog-panel > header .header-icon){width:34px;height:34px;flex-basis:34px;border-radius:9px;background:rgb(255 183 77/.12);color:#ffb74d}
  .hidden-sparks-dialog :global(.dialog-panel h2){font-size:.9rem;font-weight:720;color:var(--text-primary)}
  .hidden-sparks-dialog :global(.dialog-panel .heading p){font-size:.65rem}
  .hidden-sparks-dialog :global(.dialog-panel > .content){max-height:min(68vh,650px)}
  .hidden-sparks-dialog :global(.dialog-panel > footer .ui-button){font-size:.78rem}
  .hidden-count{padding:3px 7px;border-radius:999px;background:rgb(255 183 77/.12);color:#ffb74d;font-size:.62rem;font-weight:700;white-space:nowrap}
  .hidden-sparks-content{display:flex;flex-direction:column;gap:13px;min-width:0}
  .selection-section{display:flex;flex-direction:column;gap:3px;padding-top:11px;border-top:1px solid var(--dialog-soft-border)}
  .selection-heading{display:flex;align-items:center;gap:10px}.selection-heading>span{min-width:0;display:flex;flex-direction:column}.selection-heading strong{color:var(--text-secondary);font-size:.72rem;line-height:1.2}.selection-heading small{color:var(--text-muted);font-size:.62rem;line-height:1.15}
  .clear-button{margin-left:auto;padding:4px 8px;border:0;border-radius:6px;background:transparent;color:var(--text-muted);cursor:pointer;font:inherit;font-size:.62rem;white-space:nowrap}.clear-button:hover{color:#ffb74d;background:rgb(255 183 77/.08)}
  .hidden-list{display:flex;align-items:center;flex-wrap:wrap;gap:5px}.hidden-chip{min-width:0;max-width:100%;display:inline-flex;align-items:center;gap:5px;padding:3px 5px 3px 3px;border:1px solid var(--dialog-border);border-radius:7px;background:var(--dialog-muted-bg);color:var(--text-secondary);cursor:pointer;font:inherit;font-size:.64rem}.hidden-chip img{width:22px;height:22px;object-fit:contain}.hidden-chip span{min-width:0;overflow-wrap:anywhere}.hidden-chip :global(svg){flex:none;color:var(--text-muted)}.hidden-chip:hover{border-color:rgb(255 183 77/.36);background:rgb(255 183 77/.06)}
  .empty-selection{min-height:40px;display:flex;align-items:center;justify-content:center;gap:6px;color:var(--text-muted);font-size:.66rem}
  @media(max-width:560px){.hidden-sparks-dialog :global(.dialog-panel .heading p){display:none}}
  @media (max-width:767px) {.hidden-sparks-dialog :global(.dialog-panel > .content){max-height:none}.hidden-chip,.clear-button{min-height:var(--touch-target);min-width:var(--touch-target)}}
</style>

// src/app/components/hidden-sparks-dialog/hidden-sparks-dialog.component.ts
import { CommonModule } from '@angular/common';
import { Component, Inject } from '@angular/core';
import {
  MAT_DIALOG_DATA,
  MatDialogModule,
  MatDialogRef,
} from '@angular/material/dialog';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatTooltipModule } from '@angular/material/tooltip';
import {
  WhiteFactorPickerSelection,
  WhiteFactorTypePickerComponent,
} from '../database-filter/white-factor-type-picker/white-factor-type-picker.component';
import { Factor, FactorService } from '../../services/factor.service';

export interface HiddenSparksDialogData {
  factors: Factor[];
  hiddenFactorIds: number[];
}

@Component({
  selector: 'app-hidden-sparks-dialog',
  standalone: true,
  imports: [
    CommonModule,
    MatDialogModule,
    MatButtonModule,
    MatIconModule,
    MatTooltipModule,
    WhiteFactorTypePickerComponent,
  ],
  templateUrl: './hidden-sparks-dialog.component.html',
  styleUrl: './hidden-sparks-dialog.component.scss',
})
export class HiddenSparksDialogComponent {
  hiddenFactorIds: number[];

  constructor(
    @Inject(MAT_DIALOG_DATA) public data: HiddenSparksDialogData,
    private dialogRef: MatDialogRef<HiddenSparksDialogComponent, number[]>,
    private factorService: FactorService,
  ) {
    this.hiddenFactorIds = this.normalizeIds(data.hiddenFactorIds);
  }

  get hiddenFactorSelections(): readonly { factorId: number }[] {
    return this.hiddenFactorIds.map(factorId => ({ factorId }));
  }

  addFactors(selection: WhiteFactorPickerSelection): void {
    this.hiddenFactorIds = this.normalizeIds([
      ...this.hiddenFactorIds,
      ...selection.factorIds,
    ]);
  }

  removeFactor(factorId: number): void {
    this.hiddenFactorIds = this.hiddenFactorIds.filter(id => id !== factorId);
  }

  clearAll(): void {
    this.hiddenFactorIds = [];
  }

  save(): void {
    this.dialogRef.close(this.hiddenFactorIds);
  }

  getFactorName(factorId: number): string {
    return this.findFactor(factorId)?.text ?? `Factor ${factorId}`;
  }

  getFactorIcon(factorId: number): string | null {
    const factor = this.findFactor(factorId);
    return factor
      ? this.factorService.getFactorImageUrl({
          factorId: String(factor.id),
          level: 1,
          name: factor.text,
          type: factor.type,
        })
      : null;
  }

  trackFactor(_index: number, factorId: number): number {
    return factorId;
  }

  private findFactor(factorId: number): Factor | undefined {
    return this.data.factors.find(factor => Number(factor.id) === factorId);
  }

  private normalizeIds(ids: readonly number[]): number[] {
    return [...new Set(ids.map(Number).filter(id => Number.isFinite(id) && id > 0))]
      .sort((left, right) => left - right);
  }
}

<section class="hidden-sparks-dialog">
  <header class="dialog-header">
    <span class="header-icon">
      <mat-icon>visibility_off</mat-icon>
    </span>
    <span class="header-copy">
      <strong>Hide Sparks</strong>
      <small>Choose white factors that should be hidden from every inheritance result.</small>
    </span>
    <span class="hidden-count">{{ hiddenFactorIds.length }} hidden</span>
    <button
      mat-icon-button
      type="button"
      class="close-btn"
      mat-dialog-close
      aria-label="Close Hide Sparks dialog">
      <mat-icon>close</mat-icon>
    </button>
  </header>

  <mat-dialog-content class="dialog-content">
    <app-white-factor-type-picker
      browseLabel="Find white factors"
      [embedded]="true"
      [showPriority]="false"
      [allowSelectionToggle]="true"
      actionVerb="Hide"
      [factors]="data.factors"
      [selectedFactors]="hiddenFactorSelections"
      (addFactors)="addFactors($event)"
      (removeFactor)="removeFactor($event)">
    </app-white-factor-type-picker>

    <section class="selection-section">
      <div class="selection-heading">
        <span>
          <strong>Hidden sparks</strong>
          <small>Remove a spark here to show it again.</small>
        </span>
        <button
          *ngIf="hiddenFactorIds.length"
          type="button"
          class="clear-button"
          (click)="clearAll()">
          Clear all
        </button>
      </div>

      <div class="hidden-list" *ngIf="hiddenFactorIds.length; else emptySelection">
        <button
          *ngFor="let factorId of hiddenFactorIds; trackBy: trackFactor"
          type="button"
          class="hidden-chip"
          (click)="removeFactor(factorId)"
          [matTooltip]="'Show ' + getFactorName(factorId)">
          <img *ngIf="getFactorIcon(factorId) as iconUrl" [src]="iconUrl" alt="">
          <span>{{ getFactorName(factorId) }}</span>
          <mat-icon>close</mat-icon>
        </button>
      </div>

      <ng-template #emptySelection>
        <div class="empty-selection">
          <mat-icon>visibility</mat-icon>
          <span>No sparks are hidden.</span>
        </div>
      </ng-template>
    </section>
  </mat-dialog-content>

  <mat-dialog-actions align="end" class="dialog-actions">
    <button mat-button type="button" class="cancel-btn" mat-dialog-close>Cancel</button>
    <button mat-flat-button type="button" class="save-btn" (click)="save()">
      <mat-icon>check</mat-icon>
      Save {{ hiddenFactorIds.length }} hidden
    </button>
  </mat-dialog-actions>
</section>
